language: node_js
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
node_js:
  - '8'
install:
  - yarn
script:
  - yarn run build
cache:
  yarn: true
  directories:
    - node_modules
